### ISSUE TITLE
Create a new release for module support

### ISSUE THREAD

**Issue by kyle-ngrok** [sony/gobreaker#23]
Go modules landed a few versions ago. Could you tag the a new release as `v0.5.0`? Go expects tag names to have a `v` prefix. Thanks!

**Comment by YoshiyukiMineo** [comment]
Thank you for your feedback.

I have added the `v` prefix:
https://github.com/sony/gobreaker/releases/tag/v0.4.1

**Comment by kyle-ngrok** [comment]
Thank you!
