### ISSUE TITLE
Does this really require go 1.12?

### ISSUE THREAD

**Issue by cep21** [sony/gobreaker#24]
The go.mod file is set to work only with `go 1.12`.  When building with `go 1.11` I get errors around which version of Go is required.  Is `go 1.12` required?  Can this limitation be removed from the go.mod?

**Comment by vtolstov** [comment]
what is the benefit of using go 1.11 and not use go 1.12? (with coming 1.13 release)

**Comment by cep21** [comment]
There is none.  I'm trying to compare libraries and want to be accurate or not on stating that sony/gobreaker requires go 1.12. (which it currently appears to since it does not build as a dependency on 1.11)

**Comment by vtolstov** [comment]
IMHO i think that gobreaker requirement need to still the go 1.12. most of the projects move to go 1.12 now as hard dep.

**Comment by YoshiyukiMineo** [comment]
I have confirmed that gobreaker works well in Go 1.10, 1.11 and 1.12.
https://github.com/sony/gobreaker/blob/master/.travis.yml#L3-L5
