### ISSUE TITLE
May I request a new release with tag

### ISSUE THREAD

**Issue by pelliu** [sony/gobreaker#33]
Hi,

Thanks a lot for your library, it's really helpful!

When I check the release, the latest is 0.4.1, which was published in May 2019, but the latest merge was in Jan 2021, I can use go mod to get the latest commit change, however, when we request 3rd party library approval from my company, maybe it would not be approved, so may I request a new release with tag 0.4.2? Really appreciate it!

**Comment by YoshiyukiMineo** [comment]
Sorry for the late reaction. I have added the new tag v0.5.0.
