### ISSUE TITLE
Tag SemVer releases?

### ISSUE THREAD

**Issue by akshayjshah** [sony/gobreaker#8]
Hi! I notice that this project doesn't have any [tagged releases](https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases). Would you mind adding some [SemVer](http://semver.org/)-compatible release tags? It would really, really help those of us using [`dep`](http://github.com/golang/dep) and similar tools.

**Comment by YoshiyukiMineo** [comment]
Sorry for late reply. I have introduced SemVer.

**Comment by akshayjshah** [comment]
Thanks!
